# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BWMapping.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BWMapping(object):
    def setupUi(self, BWMapping):
        BWMapping.setObjectName("BWMapping")
        BWMapping.resize(518, 374)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BWMapping.sizePolicy().hasHeightForWidth())
        BWMapping.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("thread_16xLG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BWMapping.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BWMapping)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 121, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.partialmap_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.partialmap_radio.setGeometry(QtCore.QRect(20, 20, 82, 31))
        self.partialmap_radio.setChecked(True)
        self.partialmap_radio.setObjectName("partialmap_radio")
        self.fullmap_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.fullmap_radio.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.fullmap_radio.setObjectName("fullmap_radio")
        self.map_connectivity_combo = QtWidgets.QComboBox(self.centralwidget)
        self.map_connectivity_combo.setGeometry(QtCore.QRect(30, 140, 151, 22))
        self.map_connectivity_combo.setObjectName("map_connectivity_combo")
        self.map_startpoint_combo = QtWidgets.QComboBox(self.centralwidget)
        self.map_startpoint_combo.setGeometry(QtCore.QRect(240, 140, 241, 22))
        self.map_startpoint_combo.setEditable(True)
        self.map_startpoint_combo.setObjectName("map_startpoint_combo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 110, 181, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 91, 16))
        self.label_3.setObjectName("label_3")
        self.generate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.generate_pushButton.setGeometry(QtCore.QRect(400, 210, 75, 23))
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(400, 290, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(400, 250, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.BI7_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.BI7_checkBox.setGeometry(QtCore.QRect(30, 200, 171, 17))
        self.BI7_checkBox.setObjectName("BI7_checkBox")
        self.flowVol_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.flowVol_checkBox.setGeometry(QtCore.QRect(30, 220, 181, 17))
        self.flowVol_checkBox.setObjectName("flowVol_checkBox")
        self.storedRec_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.storedRec_checkBox.setGeometry(QtCore.QRect(30, 240, 171, 17))
        self.storedRec_checkBox.setObjectName("storedRec_checkBox")
        self.queries_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.queries_checkBox.setGeometry(QtCore.QRect(30, 260, 151, 17))
        self.queries_checkBox.setObjectName("queries_checkBox")
        BWMapping.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BWMapping)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        BWMapping.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BWMapping)
        self.statusbar.setObjectName("statusbar")
        BWMapping.setStatusBar(self.statusbar)
        self.fileRegenerate_Database = QtWidgets.QAction(BWMapping)
        self.fileRegenerate_Database.setObjectName("fileRegenerate_Database")
        self.actionLocate_dot = QtWidgets.QAction(BWMapping)
        self.actionLocate_dot.setObjectName("actionLocate_dot")
        self.menuFile.addAction(self.fileRegenerate_Database)
        self.menuFile.addAction(self.actionLocate_dot)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(BWMapping)
        QtCore.QMetaObject.connectSlotsByName(BWMapping)

    def retranslateUi(self, BWMapping):
        _translate = QtCore.QCoreApplication.translate
        BWMapping.setWindowTitle(_translate("BWMapping", "BW Mapping Tool"))
        self.groupBox_2.setTitle(_translate("BWMapping", "Map Type"))
        self.partialmap_radio.setText(_translate("BWMapping", "Partial"))
        self.fullmap_radio.setText(_translate("BWMapping", "Full"))
        self.label.setText(_translate("BWMapping", "Map Connectivity"))
        self.label_2.setText(_translate("BWMapping", "Partial Map Starting Object"))
        self.label_3.setText(_translate("BWMapping", "Extra Information:"))
        self.generate_pushButton.setText(_translate("BWMapping", "Generate"))
        self.exitButton.setText(_translate("BWMapping", "Exit"))
        self.BI7_checkBox.setText(_translate("BWMapping", "BI7 Converted Flows"))
        self.flowVol_checkBox.setText(_translate("BWMapping", "Flow Volumes for Last Run"))
        self.storedRec_checkBox.setText(_translate("BWMapping", "Stored Record Count"))
        self.queries_checkBox.setText(_translate("BWMapping", "Show Queries"))
        self.menuFile.setTitle(_translate("BWMapping", "File"))
        self.fileRegenerate_Database.setText(_translate("BWMapping", "Regenerate Database"))
        self.actionLocate_dot.setText(_translate("BWMapping", "Locate \'dot\' Executable"))

